version: '3'
services:
  app:
    build: .
    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=lolo"
      - "traefik.frontend.rule=Host:bet-bot.sltcestloic.dev"
      - "traefik.port=443"

networks:
  traefik:
    name: traefik_webgateway
    external: true

