version: '3.8'

services:
  front:
    build:
      dockerfile: Dockerfile
    container_name: betbotsite
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - "127.0.0.1:4201:3000"
    restart: always
